version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: budget_assistant_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: budget_assistant
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - budget_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d budget_assistant"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: budget_assistant_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - budget_network
    depends_on:
      - postgres

networks:
  budget_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: